### ISSUE TITLE
File PasswordPolicyType is missing

### ISSUE THREAD

**Issue by svewap** [fschmtt/keycloak-rest-api-client-php#1]
Hi! This file was not checked into the repository.
> PHP Fatal error:  Uncaught Error: Class 'Fschmtt\Keycloak\Representation\PasswordPolicyType' not found in /root/migration/vendor/fschmtt/keycloak-rest-api-client-php/src/Mapper/JsonToServerInfoMapper.php:86

Thanks, Sven

**Comment by fschmtt** [comment]
Hey, thanks for letting me know ;)

Added the missing file, but please keep in mind that this project is missing on so much more files, tests and so on - so don't use it in production.
If you'd like to contribute, please feel free, I'd appreciate it!
