### ISSUE TITLE
`hashedSaltedValue` missing from `Credential` representation

### ISSUE THREAD

**Issue by elnurvl** [fschmtt/keycloak-rest-api-client-php#109]
It is not straightforward to create a credential representation out of an existing bcrypt hash value due to the lack of `hashedSaltedValue`.

A user would need to decompose the hash manually before making a Credential representation.

**Comment by fschmtt** [comment]
Hey, I'm out for the next 5 days, so please don't wonder when I'm not responding 😅

**Comment by fschmtt** [comment]
Would it be sufficient to just add the missing property to the representation class?

I tried it locally, but I cannot generate a client with credentials that has the `hashedSaltedValue` available.

Additionally, the property is deprecated: https://www.keycloak.org/docs-api/25.0.0/javadocs/org/keycloak/representations/idm/CredentialRepresentation.html#hashedSaltedValue

What would you suggest to solve your issue? 🤔

**Comment by prajwaldivate** [comment]
Hey @fschmtt 

I am looking forward to use this fix in my project. I noticed that the commit is currently on the credential-properties branch. Are there any plans to merge this into the main branch soon?

Thanks!

**Comment by fschmtt** [comment]
Hey @prajwaldivate if you could, please verify that https://github.com/fschmtt/keycloak-rest-api-client-php/pull/120 works for you, then I'll happily merge it 🙂
