### ISSUE TITLE
Sending body to executeActionsEmail()

### ISSUE THREAD

**Issue by jeanatpi** [fschmtt/keycloak-rest-api-client-php#113]
Hi,

Reading the code of executeActionsEmail() I don't see any options to send a body containing the list of actions.

Do I miss something?

For me we should be able to send a body parameter containing a JSON array of string + optionally a client_id, lifespan and redirect_uri.

If you are open to contributions we could maybe contribute to the project.

Jean

**Comment by fschmtt** [comment]
Hey @jeanatpi, yes you're right, the library is currently missing this possibility.

It needed some refactoring (which I'm not too happy about 😅) but feel free to try out https://github.com/fschmtt/keycloak-rest-api-client-php/pull/115.

Your call should look something like this:
```php
$keycloak->users()->executeActionsEmail(
    'master',
    'user-id',
    ['VERIFY_EMAIL', 'UPDATE_PROFILE'],
    new \Fschmtt\Keycloak\Http\Criteria([
        'client_id' => 'client-id',
        'redirect_uri' => 'http://localhost:8080',
        'lifespan' => '600',
    ])
);
```

**Comment by fschmtt** [comment]
Hey @jeanatpi, I finished the PR to be in a state where I would be fine with merging it.

Would be nice if you could give me some feedback on this issue 🙂

**Comment by fschmtt** [comment]
Ping @jeanatpi, would really appreciate your feedback here 😄

**Comment by jeanatpi** [comment]
@fschmtt sorry I was out for wedding + holidays. I'll have a look, thanks :)

**Comment by fschmtt** [comment]
Hey, congratulations and no worries 😄 Take your time!

**Comment by jeanatpi** [comment]
@fschmtt thanks ;)

I just tested it and it works well. Thanks for the change.

**Comment by fschmtt** [comment]
Thanks I'll merge it then and release a new version 😊 

Thanks for your support!
