### ISSUE TITLE
Can't manage to update a user

### ISSUE THREAD

**Issue by jeanatpi** [fschmtt/keycloak-rest-api-client-php#119]
Hello,

I'm struggling updating a user via the keycloak API using this library.
I'm pretty sure the lib is not in question here but who knows.

Situation is the following:
- keycloak is setup in a container via a docker compose. Version used is 24
- php app is setup in a container in the same docker compose
- the php app is using a specific realm called "pi"
- admin user is in the "master" realm

when calling the update() method it hangs out. (the PUT request never finish).
retrieving users works, execution email action works too.

when doing PUT request directly via localhost:8080 it works.
when doing PUT request from within the php app container via keycloak:8080 it hangs up

Any idea?

**Comment by fschmtt** [comment]
Hey, no sorry, I have no idea... only piece of information I can add is that I had problems with Keycloak 24 in the GitHub workflows, too 😅 

I had to wait some more time for Keycloak to become available, but only for version 24, see here: https://github.com/fschmtt/keycloak-rest-api-client-php/blob/d92c7341f53dce77f597ff101ebca905a9d5aaba/.github/workflows/php-integration.yml#L49-L51 🤷‍♂️

**Comment by jeanatpi** [comment]
I'm going to close this ticket. Not related to this library.
I've solved our issue by upgrading keycloak to last 24.0.5 version.
