### ISSUE TITLE
Filtering via Criteria seems to have no effect on Groups::all function

### ISSUE THREAD

**Issue by p-weisk** [fschmtt/keycloak-rest-api-client-php#132]
I try and get a specific group by path by using the $criteria parameter on Groups::all to check if a group exists in this path before creating one:

`                $keycloakGroups = $this->keycloak->groups()->all($this->realm, new Criteria(['path' => '/example-path']));
`
I expect the result to be empty since no group with this path exists, but it returns all groups instead.

It doesn't work either if I use `name` instead of `path` as the criteria.

Is this user error on my part or might this be a bug?
I'm using Keycloak 25 and the latest 0.26.1 release of this library.
Thanks for the support!

**Comment by fschmtt** [comment]
Hi 👋 Could you do me a favor and try 0.25 of the library to verify?

I made quite a big refactoring in 0.26 (Symfony Serializers) and I hope this didn't break anything 😰 

I don't believe this should be an issue, though, because I only use it for serializing representations.

Thanks for your support 🙂

**Comment by p-weisk** [comment]
Hi, thanks for the quick help.
Unfortunately, downgrading to 0.25 did not change the behaviour and it still returns all groups.

**Comment by fschmtt** [comment]
Hey, first of all sorry for replying so late 🙈 

I revisited your issue and tried the `Groups::all()` endpoint, just looking at the [Keycloak REST API docs](https://www.keycloak.org/docs-api/latest/rest-api/index.html#_groups), filtering for `path` or `name` seems not to be possible at all - or it is undocumented 🤔 

I created 3 groups:
* `administrators`
* `moderators`
* `users`
and was able to get only the `administrators` group back by querying
```php
$groups = $keycloak->groups()->all($realm, new \Fschmtt\Keycloak\Http\Criteria(['search' => 'admin']));
```

Hope this helps you 🙂

**Comment by fschmtt** [comment]
Hey @p-weisk, I'm closing this issue for now.

Feel free to reopen if you still think this is a bug in the library 🙂
