### ISSUE TITLE
Property features does not exist

### ISSUE THREAD

**Issue by jprw10** [fschmtt/keycloak-rest-api-client-php#75]
Hello! A new problem seem to appears with new Keycloak version

> 17:42:25 ERROR     [app] Property "features" does not exist in "Fschmtt\Keycloak\Representation\ServerInfo"

Related to this feature: https://github.com/keycloak/keycloak/issues/17733

**Comment by fschmtt** [comment]
Thanks for bringing this up!

I tested it against all of the 22.0.x patch versions and figured out it was added in 22.0.4.

Fixed it in https://github.com/fschmtt/keycloak-rest-api-client-php/releases/tag/v0.15.1.
