### ISSUE TITLE
Authenticating Clients/Users of any Realm (not just `master`)

### ISSUE THREAD

**Issue by angelomelonas** [fschmtt/keycloak-rest-api-client-php#85]
Hi there! Thanks for this awesome Keycloak PHP client.

I don't think it's currently possible, but I have to ask: is there a way to override the default `master` Realm and specify my own Realm when creating the Keycloak client? I have a use case where I'd like to authenticate Clients/Users on the Realm level. I believe this is possible in the official [Keycloak Admin Client](https://github.com/keycloak/keycloak/tree/main/js/libs/keycloak-admin-client). Something like this should do it:

```php
// Fschmtt\Keycloak\Http\Client.php

    public function __construct(
        private readonly Keycloak              $keycloak,
        private readonly ClientInterface       $httpClient,
        private readonly TokenStorageInterface $tokenStorage,
        private readonly ?string               $realmName = null
    ) {}
    ...
    
     /**
     * @return array{access_token: string, refresh_token: string}
     */
    private function fetchTokens(): array
    {
        try {
            $response = $this->httpClient->request(
                'POST',
                $this->keycloak->getBaseUrl() . sprintf('/realms/%s/protocol/openid-connect/token', $this->realmName ?? 'master'),
                [
                    'form_params' => [
                       ...
                    ],
                ],
            );
        } catch (ClientException $e) {
            $response = $this->httpClient->request(
                'POST',
                $this->keycloak->getBaseUrl() . sprintf('/realms/%s/protocol/openid-connect/token', $this->realmName ?? 'master'),
                [
                    'form_params' => [
                        ...
                    ],
                ]
            );
        }
        ...
    }
    ...
```

What do you think? 🙂

**Comment by angelomelonas** [comment]
I think this might be out of scope of this repository. Closing it for now.

**Comment by angelomelonas** [comment]
@fschmtt let me know if you think there is space here to create a Client that also allows getting credentials for Keycloak Clients other than the Admin CLI 🙌🏼

**Comment by angelomelonas** [comment]
Thanks for getting back to me :) 

AFAIK, you are correct about the `master` realm authentication. At least for my purposes, having the ability to request an access token for non-admin clients/users would be great. 

Perhaps we can extend this repository to not only be intended for the Admin API, but to also be more general? For starters, maybe we can create an interface for `Client`, with multiple implementations depending on your use case. For example, you could have `AdminClient` or `RealmClient` (and maybe `UserClient`, but I'm not too fond of the naming), with the former using the `admin-cli` and the latter only using normal client credentials:

```JSON
"grant_type": "client_credentials",
"client_id": "client-id",
"client_secret": "client-secret"
```

That should be pretty straightforward. The part I am struggling a bit with is what to do about the `Keycloak` class? So far I've come up with:
- Creating two or more separate implementations of Keycloak (`AdminKeycloak` and `RealmKeycloak`) that each use the appropriate Client
- Adding `private readonly string $clientType = 'admin'` to the `Keycloak` constructor, as well adding a new `KeycloakClientInterface` (that each client type can implement), along with a `KeycloakClientFactory` that can create the appropriate client in the `Keycloak` constructor: `$this->client = KeycloakClientFactory::create($this->clientType, $this);`

The second one might be the best in terms of breaking changes. Let me know, and I can draft a PR 👍🏼

**Comment by fschmtt** [comment]
Thanks for your thoughts on this 😄 

To me it sounds like you are looking for a library that can handle OAuth and/or OIDC authentication (e.g. https://github.com/thephpleague/oauth2-client) 🤔

I'm against opening this library up in terms of making it more general. There are a lot of libraries out there, which implement the OAuth/OIDC authentication (and probably do it better than this library).

Additionally, there's currently no way to retrieve the `access_token` and `refresh_token` from the internals of my library.

**Comment by angelomelonas** [comment]
Absolutely no pressure on extending this library 😄 🙌🏼 

But I think I may have explained my use case poorly. This library does exactly what I need, except that it only authenticates the Admin user in the `master` realm instead of (for example) a Confidential Client created in another Realm. 

By making some minor tweaks, I've managed to use this library as I need for my locally running Keycloak instance. That includes things like getting/searching for users, creating users, creating clients, accessing custom endpoints, etc. Basically all the actions in the `/resource` directory.
 
This library is quite close to providing what the [Java Keycloak Admin Client](https://github.com/keycloak/keycloak/blob/346c2926f6e148ad2e3c2c8766c066ed65b2e8ce/integration/admin-client-jee/src/main/java/org/keycloak/admin/client/Keycloak.java#L44) provides, which is what I would've used if I didn't have to do this in PHP 😅 

In the mean time, I've spent a bit more time trying to come up with a "clean" solution. Perhaps I should open up a draft PR and you can have a look at what I mean 🙂

**Comment by fschmtt** [comment]
I believe it would be sufficient if it was possible to change the authentication details like
* realm,
* client_id
* grant_type
* ... etc.

But I might be wrong, because I'm not sure I'm exactly understanding your use case and explanations 😅

**Comment by fschmtt** [comment]
Hey, I will close this one due to inactivity.

Feel free to reopen if you want to proceed on this issue 🙂

**Comment by angelomelonas** [comment]
Hey @fschmtt, apologies for not responding sooner! I think it's okay to keep it closed for now. If I have some time in the future, we can reopen it :)

**Comment by charly-ffss** [comment]
Hi,

I'm trying to use your library to access the Keycloak admin API for a specific realm, but I'm encountering the following error:


"Call to a member function getVersion() on null"
Root cause:
The Keycloak class calls fetchVersion() during initialization, which attempts to retrieve serverInfo()->get()->getSystemInfo()->getVersion(). This seems to fail with my current credentials.

Possible issues:

Missing permissions: My authenticated user has view-realm and manage-users permissions on the target realm, but perhaps needs additional permissions to access serverInfo.
Master realm requirement: I suspect that serverInfo might require authentication against the master realm or elevated admin privileges.
Questions:

Is it expected that users need master realm admin rights to use this library, even for restricted realm administration?
If not, what specific permissions are required to access serverInfo?
Would it be possible to make the library more flexible to support restricted realm administration (where the user only has permissions on a specific realm)?
Additional context:
I'm using the Password grant type with a service account that has limited permissions scoped to a single realm, to follow the principle of least privilege.

Thanks for your help!
