### ISSUE TITLE
Support for client retrieval by client ID

### ISSUE THREAD

**Issue by elnurvl** [fschmtt/keycloak-rest-api-client-php#98]
I have noticed that retrieving clients by client ID is not possible. The confusion is compounded by naming the client UUID parameter as client ID, leading developers to mistakenly believe that the library expects a client ID for resource retrieval.

Adding a method at least like users()->search(['clientId' => 'client-id']) would simplify the process.

**Comment by fschmtt** [comment]
Hey @elnurvl,

generally you can provide additional `Criteria` to the `search()` method:

```
$users->search('master', new Criteria(['username' => 'foo']));
```

However, according to the Keycloak docs, filtering for a `clientId` does not seem to be possible.

**Comment by elnurvl** [comment]
Sorry, my bad: I meant searching clients by clientID, which is possible according to the API docs. It would look like this:

```
->clients->search('realm', ['clientId' => 'clientId']);
```

Do you think it makes sense to rename the parameter name `clientId` to `clientUuid` accross all methods to avoid confusion? This is how Keycloak API docs refer to the parameter as well.

**Comment by fschmtt** [comment]
Are you referring to `GET /admin/realms/{realm}/clients`?

The parameter there is called `clientId`. As the `Criteria` is just "passed through" to the query, there's no need or possibility to rename parameter.

**Comment by elnurvl** [comment]
I hope, below images will make my points clear.

Here you can see the parameter is called as `client-uuid`. You can rename the argument of the relevant method and exception messages accordingly to conform to the docs and avoid confusion.

![image](https://github.com/fschmtt/keycloak-rest-api-client-php/assets/7970970/a4c3a4c8-b039-47eb-93ad-30562ad25ba3)

Here, you can see the API
allows you to pass a search parameter for clients like in users endpoint. This allows you to get clients by `client-id`.

![image](https://github.com/fschmtt/keycloak-rest-api-client-php/assets/7970970/905e74e9-10b0-4f6b-9041-eecb99797dbb)

**Comment by fschmtt** [comment]
Ah, now I get your point.

Seems that they also renamed the parameter from `{id}` to `{clientUuid}` for clarification.

As of my knowledge the `{id}` of a representation is always referring to the UUID.

Renamed it in #104
