### ISSUE TITLE
Missing credentials in the User representation

### ISSUE THREAD

**Issue by elnurvl** [fschmtt/keycloak-rest-api-client-php#99]
According to the REST API documentation, `GET /admin/realms/{realm}/users` should include list of credentials users possess. But it is not in the response even for users with credentials. I am not sure if this is an intentional restriction from Keycloak or an oversight in the client, but unfortunately, there is no support for `GET /admin/realms/{realm}/users/{user-id}/credentials` endpoint at all to rely on as an alternative solution. Having an access to credentials data would particularly helpful to get information on password renewals, account activation time.

**Comment by fschmtt** [comment]
Hey @elnurvl,

thanks for opening this issue.

I created a PR to add the mentioned endpoint.

At the same time, it seems that the `GET /admin/realms/{realm}/users` returns only a partial `UserRepresentation` as seen here:

```json
[
    {
        "id": "c7f4316a-7a81-48cd-a60a-c92544bcc628",
        "username": "17ad6571-3ecf-4c6c-8102-bbe794a73118",
        "emailVerified": false,
        "createdTimestamp": 1716633308631,
        "enabled": true,
        "totp": false,
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    },
    {
        "id": "f460d385-663a-4c7c-8034-8376d0def6e1",
        "username": "381a9a00-c7c7-47db-ae5f-8519b5263557",
        "emailVerified": false,
        "createdTimestamp": 1716633534673,
        "enabled": false,
        "totp": false,
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    },
    {
        "id": "07f25c15-2166-4869-9d62-74f21d2254c1",
        "username": "96e2fe87-a627-46f6-9747-1f8e08136c79",
        "emailVerified": false,
        "createdTimestamp": 1716633398209,
        "enabled": false,
        "totp": false,
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    },
    {
        "id": "b4f25a05-a0cc-4db6-b804-2c40b0c36aa1",
        "username": "admin",
        "emailVerified": false,
        "createdTimestamp": 1716633297554,
        "enabled": true,
        "totp": false,
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    }
]
```

Hope the additional endpoint solves this issue for you 🤞

**Comment by elnurvl** [comment]
Thank you for a very quick resolution! Yes, this will do the job.

I wonder why the API would not give the full representation despite the API docs saying it should though.

**Comment by fschmtt** [comment]
I observed this behaviour of partial representations for multiple endpoints.

I'll close this issue then, thanks for the feedback 😀

**Comment by elnurvl** [comment]
@fschmtt , I have realized PHP 8.1 support was dropped with the new release. We still won't be able to use the feature, unfortunately. Is there some kind of defined policy regarding the minimum supported PHP version?

**Comment by fschmtt** [comment]
No, I currently don't have a policy set up.

What I'm currently doing is, I'm looking at https://www.php.net/supported-versions.php and drop support for a version that does not have _Active Support_ after some time.

I'm currently thinking about supporting the versions that have `Security Support`, see #105

**Comment by elnurvl** [comment]
> I'm currently thinking about supporting the versions that have `Security Support`, see #105 

I an impressed with your responsiveness. Yes, keeping the support for versions not fully discontinued makes more sense to me.

**Comment by fschmtt** [comment]
Trying my best 😄 

You can use v0.22.0 🎉
